### ISSUE TITLE
setup request

### ISSUE THREAD

**Issue by Bra1nsen** [Math1a/DavisWeather#1]
Is there a way of connecting directly to the vantage pro2 weather station with an RJ11 USB Adapter. I mean I would like to connect my PC (Linux/Windows) directly so the whitebox of the vantage pro2 without using any kind of console or base station.

![davis-instruments-vantage-pro2-dav-6152eu-funk-wetterstation](https://user-images.githubusercontent.com/58213050/169802016-28e80c26-e02a-4e14-a22e-4547022d4726.jpg)

**Comment by Math1a** [comment]
I am afraid there isn't, at least not using this repository.
My setup uses a WeatherLink USB data logger, which is the one that is doing all the serial communication. The data logger connects to the console. I am just reading and translating the transmitted data.
